# title & subtitle
#   Title and subheading for your site. Used on the layout page and 
#   will be overriden in every page titles.
#
title: Test Village
subtitle: (change this text in config/village.yml)

# author
#   You should really specify your content's author when generating an
#   Atom feed. Specify at least one of name, uri or email, and Village will
#   include it in your feed. See the Atom spec for more info:
#
# http://www.atomenabled.org/developers/syndication/atom-format-spec.php#element.feed
#
author:
  name: Fajri Fachriansyah
  uri: http://yourhomepage.com
  email: fajri82@gmail.com

# layout
#     The name of the layout file to be used by Village specified in "app/views/layouts",
#     village will look for every pages / articles layouts for every request.
#
layout: application

# page_size
#     the page size / PER_PAGE used by Kaminari for paginate your articles,
#     the default is 5
#
# page_size: 5

# disqus_short_name
#   If you want to use the Disqus service (http://disqus.com) to display
#   comments on your site, register a Disqus account and then specify your
#   site's short name here. A comment form will automatically be added to
#   the bottom of your pages.
#
# disqus_short_name: mysite

# google_analytics_code
#     Set this if you want Google Analytics to track traffic on your site.
#     Probably best not to set a default value, but to set it in production.
#
#     The production settings are used if you're deploying to Heroku, so
#     scroll down a bit to set it in production even if you're not deploying
#     to your own server.
#
# google_analytics_code: "UA-???????-?"
